# Generated by Django 4.0.4 on 2022-06-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225, null=True)),
                ('under', models.CharField(max_length=225)),
                ('gp_behaves_like_sub_ledger', models.BooleanField(default=False)),
                ('nett_debit_credit_bal_reporting', models.BooleanField(default=False)),
                ('used_for_calculation', models.BooleanField(default=False)),
                ('method_to_allocate_usd_purchase', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
