# Generated by Django 4.0.4 on 2022-06-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=225)),
                ('formal_name', models.CharField(max_length=225)),
                ('ISO_code', models.CharField(max_length=225)),
                ('decimal_places', models.CharField(default=2, max_length=225)),
                ('show_in_millions', models.CharField(max_length=225)),
                ('suffix_to_amount', models.CharField(max_length=225)),
                ('space_symbol_amount', models.CharField(max_length=225)),
                ('word_after_decimal', models.CharField(max_length=225)),
                ('decimal_no_in_words', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('voucher_type', models.CharField(max_length=225)),
                ('abbreviation', models.CharField(max_length=225)),
                ('active_this_voucher_type', models.BooleanField()),
                ('method_voucher_numbering', models.CharField(max_length=225)),
                ('use_effective_date', models.BooleanField()),
                ('allow_zero_value_trns', models.BooleanField()),
                ('allow_naration_in_voucher', models.BooleanField()),
                ('enable_default_ac_allocation', models.BooleanField()),
                ('track_additional_cost_purchase', models.BooleanField()),
                ('use_as_manf_journal', models.BooleanField()),
                ('print_voucher_af_save', models.BooleanField()),
                ('print_formal_recept', models.BooleanField()),
                ('default_juridiction', models.CharField(max_length=225)),
                ('default_title', models.CharField(max_length=225)),
                ('alter_decalaration', models.BooleanField()),
            ],
        ),
    ]
